# Generated by Django 5.2.1 on 2025-12-16 10:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RenameJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('playlist_url', models.TextField()),
                ('selected_files', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('completed', 'completed'), ('failed', 'failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('matches', models.JSONField(default=list)),
                ('rename_commands', models.JSONField(default=list)),
                ('statistics', models.JSONField(default=dict)),
                ('playlist_title', models.CharField(blank=True, max_length=255)),
                ('video_titles', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='YouTubeCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.CharField(max_length=100, unique=True)),
                ('video_data', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
